name: Build Android App (Local)

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-local:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: npm install

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Install Android SDK components
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;27.1.12297006" || true

      - name: Clean and prebuild Android project
        run: |
          rm -rf android
          npx expo prebuild --platform android

      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: android-apk-local
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7

      - name: Record build artifact in database
        if: steps.upload-artifact.outputs.artifact-id
        run: |
          # Construct the artifact download URL
          ARTIFACT_ID="${{ steps.upload-artifact.outputs.artifact-id }}"
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${ARTIFACT_ID}"
          
          # API base URL
          API_BASE_URL="https://supplemate-api2.impaas.uk"
          
          echo "Recording artifact in database..."
          echo "Artifact ID: ${ARTIFACT_ID}"
          echo "Artifact URL: ${ARTIFACT_URL}"
          
          # Record the artifact in the database
          curl -X POST "${API_BASE_URL}/artifacts" \
            -H "Content-Type: application/json" \
            -d "{
              \"platform\": \"android\",
              \"download_url\": \"${ARTIFACT_URL}\",
              \"build_commit_hash\": \"${{ github.sha }}\"
            }" \
            --fail \
            --show-error \
            --silent && echo "✅ Artifact successfully recorded in database!" || echo "⚠️ Warning: Failed to record artifact in database"
